### ISSUE TITLE
Docs: what APIs are not supported?

### ISSUE THREAD

**Issue by ebidel** [ampproject/worker-dom#1]
README should mention what is and is not supported. 

Doing a quick poke around, things like `document.querySelector` and `.innerHTML` are not, but it would be nice to know the API surface that's covered.

**Comment by kristoferbaxter** [comment]
Good point @ebidel. I'll assign this task to me for completion.

**Comment by niutech** [comment]
Why can't `querySelector` or `querySelectorAll` be supported? E.g. [domino](https://github.com/fgnass/domino) uses [zest](https://github.com/chjj/zest) and [jsdom](https://github.com/jsdom/jsdom) uses [sizzle](https://github.com/jsdom/jsdom/blob/092e777a778842b66c5d280257f92951937f8fa5/lib/jsdom/selectors/sizzle.js) for that.

**Comment by cramforce** [comment]
querySelector is already on the radar. It can be supported.

**Comment by niutech** [comment]
How about querySelectorAll?

**Comment by AhsanE** [comment]
Are canvas and WebGl going to be supported?

**Comment by pbadenski** [comment]
Not sure if this is the right place.. I'm trying to port a library to worker-dom and also identified `getComputedStyle` as not supported.

**Comment by choumx** [comment]
First pass added in #303 here: https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md

**Comment by kristoferbaxter** [comment]
Marking as closed, let us know if the compat table doesn't meet your needs.
