### ISSUE TITLE
Possible to support childNode.replaceWith and childNode.remove?

### ISSUE THREAD

**Issue by Slapbox** [ampproject/worker-dom#1023]
I've been reviewing the capabilities and it's really impressive!

I was hoping we'd be able to switch over to using worker-dom, but I found as I got to the bottom of our code, the last two methods we use are not supported.

Is it possible to add support for `childNode.replaceWith` and `childNode.remove`? 

Is there somewhere that the team has a roadmap? Thanks very much for sharing your hard work!

**Comment by samouri** [comment]
Hey @Slapbox, 

We don't have any features on the roadmap for now.

I believe we already have `Node.remove` implemented:

https://github.com/ampproject/worker-dom/blob/5aa157976f692c760eae65cdb375523f86d1e129/src/worker-thread/dom/Node.ts#L375-L383

We likely just need to update the compat table.

Regarding `replaceWith`, I don't think we have that implemented. We are always open to outside contribution in case you'd like to create a pull request adding support!

**Comment by Slapbox** [comment]
Thanks very much for your reply @samouri! I'd love to contribute to getting those features included, but I wouldn't even know where to begin.

**Comment by samouri** [comment]
I believe the new method `replaceWith` would go in `Node.ts` file. You should follow the spec as [explained in mdn](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith). Particularly useful is the Polyfill.

You'd then want to create a new file called `src/test/node/replaceWith.test.ts` and follow a similar pattern to other methods, like https://github.com/ampproject/worker-dom/blob/main/src/test/node/remove.test.ts

**Comment by kristoferbaxter** [comment]
I haven't made a contribution for a while to this repo, so I'll take this on.

**Comment by samouri** [comment]
I'll perform a release on Monday

**Comment by Slapbox** [comment]
Holy moly, thanks @kristoferbaxter for your PR and @samouri for your guidance and maintenance!

**Comment by kristoferbaxter** [comment]
Released in `0.28.0`.
