### ISSUE TITLE
Feature request: Encapsulate styles using Shadow DOM

### ISSUE THREAD

**Issue by cometkim** [ampproject/worker-dom#1093]
I'm using Worker DOM to run embedded 3rd party code.

If a third-party insert style like `<style>* { color: red !important }</style>` in the Worker, it can easily affect the host.

Although it was confirmed that encapsulation was possible simply by using an element attached through a shadow root instead of directly using the base element.

Wouldn't this be nice on upstream too? If that's okay, I'll file a PR.

**Comment by samouri** [comment]
@cometkim: can you explain a bit more about the feature you want? A configurable option to place everything worker-dom operates on in the SD?

**Comment by cometkim** [comment]
I thought by simply adding attribute like `shadow-root="open"` or` "close"` onto the base element

e.g. `<div src="hello-world.js" id="upgrade-me" shadow-root="open">`

Current Behavior:
<img width="820" alt="Screen Shot 2021-09-15 at 4 38 47 PM" src="https://user-images.githubusercontent.com/9696352/133408016-237fc1bd-2dc2-4f70-acc7-db63b5bf5d43.png">

Using Shadow DOM:
<img width="856" alt="Screen Shot 2021-09-15 at 4 36 41 PM" src="https://user-images.githubusercontent.com/9696352/133408000-034c0483-9db7-42b1-9560-e2e555fde10f.png">

if `shadow-root` attr is provided, on main thread, installation gonna be on a cloned & attached element instead of the original element.
```ts
if (shadowRoot !== null) {
  const shadowRoot = baseElement.attachShadow({ mode: shadowRoot });
  const clonedElement = baseElement.cloneNode(true) as HTMLElement;
  shadowRoot.appendChild(clonedElement);

  baseElement = clonedElement;
}
```

Another option is to define and use a custom element for it from outside.

**Comment by samouri** [comment]
I like this idea! I don't have bandwidth to implement it myself now, but would be happy to accept a contribution.
Otherwise I could likely implement it before the end of the year.
