### ISSUE TITLE
Descendants of upgraded element are not present in virtual DOM when worker starts

### ISSUE THREAD

**Issue by lawnsea** [ampproject/worker-dom#11]
Currently, if an upgraded element has descendant elements, they are not present in `document.body` in the worker script.

As a user, I would expect these elements to be present in the worker's virtual DOM.

Repro: https://glitch.com/edit/#!/scarlet-clownfish

**Comment by cramforce** [comment]
As discussed in person yesterday, this is intentional, and arguably correct for client-side rendered use cases.

But there are a whole bunch of use cases that could benefit from changing the design decision.

**Comment by kristoferbaxter** [comment]
This was resolved with release `0.2.0`!
