### ISSUE TITLE
Implement `querySelector` and `querySelectorAll`

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/worker-dom#111]
Used and beloved by many web developers, and completely missing from `worker-dom`.

Let's add it in.

This description is intentionally small to allow @nainar to fill in as details rise in the implementation.

**Comment by nainar** [comment]
Logging current implementation plan per discussion:
- [ ] Implement querySelectorAll for the following:
  - [ ] class selector
  - [ ] ID selector
  - [ ] attribute selector
  - [ ] tag selector
- [ ] Implement querySelector to return the 0th item result of calling querySelector
- [ ] Wait for use case to add support for more complex selectors

**Comment by kristoferbaxter** [comment]
We'll revisit adding more complex selector support based on requested use cases.
