### ISSUE TITLE
Running demo on Windows

### ISSUE THREAD

**Issue by michalstepien** [ampproject/worker-dom#119]
Hello,
I have problem with running demo on Windows 10:

`> @ampproject/worker-dom@0.1.4 demo F:\wd\worker-dom-master
> node -r esm demo/server.mjs

file:///F:/wd/worker-dom-master/demo/server.mjs:1
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Proxy.resolve (path.js:221:7)
    at file:///F:/wd/worker-dom-master/demo/server.mjs:24:25`

**Comment by kristoferbaxter** [comment]
Believe this is resolved with #120. Will verify on a Windows machine.
