### ISSUE TITLE
Library paths for demos are not pointing in the right place

### ISSUE THREAD

**Issue by JamesMilnerUK** [ampproject/worker-dom#13]
Firstly thanks for this great library, top work! I just wanted to point out, the demos provided in the repository point at `./dist/index.mjs` and `./dist/index.js` respectively. The dist folder is actually the folder above, so to get any of the demos to work you have to change the URL to be `./../dist/index.js` or the module equivalent. 

Would you like me to raise a PR to fix this?

**Comment by kristoferbaxter** [comment]
A PR would be great. Thank you for giving it a go!
