### ISSUE TITLE
Node ID mismatch between main-thread and worker-thread

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#231]
Noticed this on 0.2.8 while testing `amp-script` using the minified worker binary. 

Results in `Uncaught TypeError: Cannot read property 'onchange' of undefined` due to undefined `target` on this line: https://github.com/ampproject/worker-dom/blob/21dc0ff12ac62c9cbb3b7d50ed901d4eb07beaa4/src/main-thread/command.ts#L126

Root cause is `consumeInitialDOM()` doesn't use node IDs from the main-thread's `skeleton`: https://github.com/ampproject/worker-dom/blob/21dc0ff12ac62c9cbb3b7d50ed901d4eb07beaa4/src/worker-thread/initialize.ts#L34-L63

Potential fix: Pass `skeleton[TransferrableKeys.index]` into the `storeNode()` invocations in `create()` to ensure that IDs of hydrated nodes are consistent between main-thread and worker-thread.

#185 (unreleased) appears to fix my repro case but I believe the implicit ordering risk remains.

**Comment by choumx** [comment]
Tangential typing issue: the main-thread's `getNode()` can return `null` given a bogus ID, so its return type should be nullable i.e. `RenderableElement | null`.

**Comment by kristoferbaxter** [comment]
Resolved as of `0.12`
