### ISSUE TITLE
Infinite recursion at CSSStyleDeclaration.getPropertyValue

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#232]
Only reproducible at current HEAD (I think starting at #185). Not reproducible on 0.2.8. 

A:
https://github.com/ampproject/worker-dom/blob/21dc0ff12ac62c9cbb3b7d50ed901d4eb07beaa4/src/worker-thread/css/CSSStyleDeclaration.ts#L68-L70

B:
https://github.com/ampproject/worker-dom/blob/21dc0ff12ac62c9cbb3b7d50ed901d4eb07beaa4/src/worker-thread/css/CSSStyleDeclaration.ts#L108-L110

A -> B -> A etc.

Results in error:
```
Uncaught RangeError: Maximum call stack size exceeded
    at CSSStyleDeclaration.getPropertyValue (...)
    at CSSStyleDeclaration.get (...)
    at CSSStyleDeclaration.getPropertyValue (...)
    at CSSStyleDeclaration.get (...)
    ...
```

Reproduced from author JS:
```js
document.getElementById('hello').addEventListener('click', ()=>{
  const el = document.createElement('h1'); // Infinite recursion starts here on click.
  el.textContent = 'Hello World!';
  document.body.appendChild(el);
});
```

Stack trace:
```
getPropertyValue (/examples/amp-script/hello-world.js:formatted:1600)
get (/examples/amp-script/hello-world.js:formatted:1557)
setProperty (/examples/amp-script/hello-world.js:formatted:1627)
set (/examples/amp-script/hello-world.js:formatted:1560)
CSSStyleDeclaration (/examples/amp-script/hello-world.js:formatted:1571)
Element (/examples/amp-script/hello-world.js:formatted:1821)
HTMLElement (/examples/amp-script/hello-world.js:formatted:2226)
createElementNS (/examples/amp-script/hello-world.js:formatted:4610)
createElement (/examples/amp-script/hello-world.js:formatted:4605)
document.getElementById.addEventListener (/examples/amp-script/hello-world.js:formatted:4892)
dispatchEvent (/examples/amp-script/hello-world.js:formatted:815)
(anonymous) (/examples/amp-script/hello-world.js:formatted:4438)
```

**Comment by kristoferbaxter** [comment]
Good find! We should add a test to prevent a regression with the fix.

**Comment by choumx** [comment]
I think the issue is this: https://github.com/ampproject/worker-dom/blob/21dc0ff12ac62c9cbb3b7d50ed901d4eb07beaa4/src/main-thread/worker.ts#L41-L43

`keys` ends up containing a bunch of integers from 0...500+ which ends up clashing with `TransferrableKeys` props. I'm guessing we actually want non-empty string values of the style keys, e.g.
```js
const keys = Object.values(document.body.style).filter(v => v.length);
```
Also, why `document.body.style` vs. `baseElement.style`?

**Comment by kristoferbaxter** [comment]
Will make a quick change here with a test.

**Comment by kristoferbaxter** [comment]
Resolved.
