### ISSUE TITLE
Release tags show wrong version number in package.json

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#251]
Expect `0.2.10` here: https://github.com/ampproject/worker-dom/blob/v0.2.10/package.json#L3

I'm guessing this is an ordering issue of `release:tag` here?

```
"npm-run-all --serial size release:tag release:git release:gren release:changelog release:git"
```

**Comment by kristoferbaxter** [comment]
Resolved with 71b8b8e.
