### ISSUE TITLE
Canvas support

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#255]
Canvas support would allow for many interesting use-cases, such as 3D previews for e-commerce and the various charting libraries.

It seems this could be done either via [`OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) or perhaps by treating method calls on `CanvasRenderingContext2D` as separate mutations (this would probably cause some minor delays, but it wouldn't be too big of an issue for use-cases like rendering a chart).

**Comment by kristoferbaxter** [comment]
Like the approach of using `OffscreenCanvas` where supported and falling back to an extended Mutation structure where it's not.

Will take this as an action item.

**Comment by choumx** [comment]
Implemented starting in #380.
