### ISSUE TITLE
Implement set innerHTML

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#283]
Needed by #19, #167 and #282. 

Also used by some [React examples](https://reactjs.org/community/examples.html) I've tried e.g. [product-compare-react](https://github.com/Rhymond/product-compare-react).

We should also discuss how to handle the async problem. For measurement, we can mark elements that set `innerHTML` as "dirty" until reconciled from main thread, and output warnings when reading from "dirty" elements.

/to @delima02 /cc @kristoferbaxter @jridgewell

**Comment by kristoferbaxter** [comment]
Similar to how we treat other getters and setters requiring synchronous access to computed layout, we can start with a `Promise` result method equivalent. Unfortunately, it cannot be a setter. (https://github.com/tc39/ecmascript-asyncawait/issues/82)

```typescript
class Element {
   public async setInnerHTMLAsync(markup: string): Promise<void> {}
}
```

This would be the second case of an `async` method replacement for a previously sync method. I'd like to ensure we have a utility for supplying the sync method with a message for developers (similar to `reflectProperties` helper).

**Comment by choumx** [comment]
`setInnerHTMLAsync` SGTM. Do you think we should leave `set innerHTML()` un-implemented? Currently it causes a runtime error e.g. in Vue.js framework code (#282):
```
Uncaught TypeError: Cannot set property innerHTML of #<Element> which has only a getter
```
IMO, we should still offer it and call `setInnerHTMLAsync()` under the hood. Dirty flag from OP optional as a dev warning.

**Comment by jridgewell** [comment]
Alternatively, we could implement this with a very-minimal HTML parser in WorkerDOM. We would then sync the nodes from the worker to the main thread, instead of worker->main->worker.

A parser could be done in a few hundred bytes if we don't need to support html-soup style fallbacks like the browsers.

**Comment by kristoferbaxter** [comment]
I'd be curious to see what the size, performance, and correctness would look like for a small parser.

**Comment by choumx** [comment]
@delima02 is looking into integrating a lightweight HTML parser for this. 

It would also avoid the need to build plumbing for syncing DOM from "main thread -> worker" (basically hydration after initial load).
