### ISSUE TITLE
Document.defaultView != WorkerDOMGlobalScope

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#291]
Likely future source of confusion.

https://github.com/ampproject/worker-dom/blob/57855f59bedf397f935240b9601869ad209bbfb6/src/worker-thread/dom/Document.ts#L63-L73

vs.

https://github.com/ampproject/worker-dom/blob/57855f59bedf397f935240b9601869ad209bbfb6/src/worker-thread/WorkerDOMGlobalScope.ts#L49-L87

**Comment by kristoferbaxter** [comment]
Fixed in #407.
