### ISSUE TITLE
Empty <amp-script> doesn't load Web Worker

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#298]
It seems that the worker is never started if `amp-script` has no children:

```
<amp-script layout=container src="/anything.js"></amp-script>
```

Not sure if this is intended behavior or not? If it is, maybe it should print an error in the console?

**Comment by kristoferbaxter** [comment]
Added a demo case for this to ensure there wasn't an issue with `WorkerDOM`. This appears to be fixed with the `0.4.0` release. 64bf82c.
