### ISSUE TITLE
textContent getter throws exception

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#326]
It seems that calling the `textContent` getter throws `Uncaught TypeError: Cannot read property 'length' of undefined`, example code:

HTML:
```
<amp-script layout=container src="script.js">
  <button id="button">Run</button>
  <div id="input">Hello</div>
</amp-script>
```

JS:
```js
document.getElementById('button').addEventListener('click', () => {
  document.getElementById('input').textContent;
});
```

Exception seems to be thrown here:
https://github.com/ampproject/worker-dom/blob/f020b73f10f04d25b67c9d406386f3e14e337292/src/worker-thread/dom/Node.ts#L112

**Comment by kristoferbaxter** [comment]
Taking a look.

**Comment by kristoferbaxter** [comment]
Couldn't reproduce with either safe mode (`amp-script` uses this version) or the default.

Can you create an example to debug against?

**Comment by choumx** [comment]
Due to `super.textContent` not being transpiled correctly in Babel "loose" mode.
