### ISSUE TITLE
Show warning when unimplemented DOM method is used

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#333]
It would be immensely helpful for testing libraries if we add "dummy" implementations for some DOM methods, e.g. replace these comments:

https://github.com/ampproject/worker-dom/blob/3e5cbe5b236ad34ffe073d128a31a2a2fdfcbab2/src/worker-thread/dom/Element.ts#L87-L106

...with implementations that just log to console that an implemented method was called. Could possibly do it in a dev version only.

**Comment by choumx** [comment]
Agreed. This is a dupe of #137.
