### ISSUE TITLE
Implement common GlobalEventHandlers e.g. onclick

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#369]
Related: #319 

Preact uses the presence of `'on' + event` for [type casing of registered event listeners](https://github.com/developit/preact/blob/3b448bb516922426fd48c10601c6b21990be380f/src/diff/props.js#L69-L81). 

E.g. if `onclick` is not implemented, then:

```jsx
<button onClick={handler()}>
```

...will result in:

```js
button.addEventListener('Click', ...); // Should be 'click'.
```

Event types are case-sensitive so this won't work.

React doesn't have this particular issue since it uses an [explicit mapping](https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/SimpleEventPlugin.js#L143-L160) but it does do something similar for [isEventSupported](https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/isEventSupported.js#L23-L38).

**Comment by kristoferbaxter** [comment]
Resolved with #661.
