### ISSUE TITLE
Adding an amp-script offsets element indexes

### ISSUE THREAD

**Issue by torch2424** [ampproject/worker-dom#436]
relates to #187

However, this is (may) already be fixed by #435 

Here is a [glitch project](https://glitch.com/edit/#!/worker-dom-amp-bug-torch2424)

[Broken 0.8.0 Example](https://worker-dom-amp-bug-torch2424.glitch.me/)

[Working filter-hydration branch example](https://worker-dom-amp-bug-torch2424.glitch.me/working.html)

cc @kristoferbaxter

**Comment by torch2424** [comment]
Discussed offline, the PR only fixes this, some of the time. Seems to depend on when the image is loaded.

**Comment by kristoferbaxter** [comment]
Fixed the remaining issue in 0950489. Wasn't using the passed down override during Initialization phase.
