### ISSUE TITLE
Configurable allowlist for mutation processors

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#477]
Allow clients to configure which mutations are allowed, e.g. by filtering executors in `MutationProcessor` constructor: https://github.com/ampproject/worker-dom/blob/443f62e348911c1e9361b4ade70cdd1606c46d67/src/main-thread/mutator.ts#L59-L70

This allows specific clients to have stricter API semantics while still having broad API support in worker-dom.

/cc @kristoferbaxter

**Comment by kristoferbaxter** [comment]
Good idea for the amp variant. I can address this quickly.
