### ISSUE TITLE
What does safe mode do?

### ISSUE THREAD

**Issue by shhnjk** [ampproject/worker-dom#48]
https://github.com/ampproject/worker-dom#safe-mode
> "Safe" mode
WorkerDOM has a special output variant that includes safety features e.g. HTML sanitization and a web worker sandbox. 

I believe HTML sanitization part is [DOMPurify](https://github.com/cure53/DOMPurify), but what is web worker sandbox? Is it WHITELISTED_GLOBALS?

And what does those intended to protect? And if possible, I'd like to also know what's not protected.

Thanks!

**Comment by kristoferbaxter** [comment]
@choumx – Can you answer this question?

**Comment by choumx** [comment]
Web workers were not designed to be a security boundary, so it's possible that browsers will add new APIs to web workers that have security implications. The worker sandbox attempts to mitigate this with an API whitelist. Other mitigations include protecting the worker plumbing code from author script subversion in the event of an XSS in the worker. That said, the sandbox is still a work in progress and pending internal security review.
