### ISSUE TITLE
Support localStorage

### ISSUE THREAD

**Issue by YangGao-yg1751** [ampproject/worker-dom#551]
## Description
According to [WorkerDOM compatibility table](https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md), `Window.localStorage` has been supported. 

> 

Window.localStorage | ✔️
-- | --

However, when I try accessing `localStorage`'s APIs in the worker thread, all of them are `undefined`. And the value of `WorkerThread.workerDom.localStorage` is just a plain object.
## Expected Result
All of the APIs of `localStorage` should exist and return correct results in worker thread. 
## Actual Result
In the scope of author script, `localStorage` is just a plain object and all of its APIs can not be accessed.

**Comment by YangGao-yg1751** [comment]
@choumx

**Comment by choumx** [comment]
Thanks for reporting this. The documentation is wrong and the localStorage plumbing is not yet supported as you mention.
