### ISSUE TITLE
[FEATURE REQUEST] Implement Window.navigator

### ISSUE THREAD

**Issue by dbarcosb** [ampproject/worker-dom#556]
https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator

Returns a reference to the Navigator object, which can be queried for information about the application running the script. For example, to modify content based on user agent.

Thanks

cc @kristoferbaxter @choumx

**Comment by choumx** [comment]
`self.navigator` accesses [`WorkerGlobalScope.navigator`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/navigator). Does WorkerNavigator not suffice for your use case?

**Comment by dbarcosb** [comment]
Hi @choumx and thanks for the quick reply. I checked the compatibility matrix and didn't find it, thus my request, but for my use case, WorkerGlobalScope is everything I need. Thanks so much!

**Comment by choumx** [comment]
We'll add it to the compat table, thanks!
