### ISSUE TITLE
Bug: `el.setAttribute('name', '')`

### ISSUE THREAD

**Issue by AngusFu** [ampproject/worker-dom#562]
## Description

```
el.setAttribute('some-attr-name', '')
```

The actual value received in main thread  is `null`. 

This does not match the real DOM world's rule.

## Reproduction

[jsbin](https://jsbin.com/kowexoqoyi/1/edit?html,output)

**Comment by choumx** [comment]
Related: https://github.com/ampproject/amphtml/issues/22371
