### ISSUE TITLE
Input value is not sync'ed unless it registers an event listener

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#588]
```js
const input = document.querySelector('input');
const button = document.querySelector('button');
button.addEventListener('click', () => {
  console.log(input.value); // Always prints "".
});
```

This is because we only fire `value` changes in event-subscription.ts, and `input` never registers an event listener.

Similar to #537.

**Comment by kristoferbaxter** [comment]
Resolved with `0.20.0` (trackable value changes) and `0.21.0` (attribute changes that also change properties).
