### ISSUE TITLE
How is memory management handled?

### ISSUE THREAD

**Issue by mdboom** [ampproject/worker-dom#6]
Forgive me using this to ask a question rather than report an issue.

I'm curious if there is anything in WorkerDOM that addresses the issue of leaking of DOM objects outlined in a similar project, via.js, [here](https://github.com/AshleyScirra/via.js#the-big-problem-leaking-memory):

> The main reason you wouldn't want to use Via.js is because currently every single DOM object you use from the worker is permanently leaked! This is because Via.js must maintain maps of object ID to the real object, so when it receives a command involving object ID 1 it knows how to find it. It's impossible to know how long the worker will hold on to these references because garbage collection is not observable in JavaScript. So the library has no way of ever removing objects from its ID map. Any time an object would normally be garbage collected, it will have one last reference in the ID map which will prevent it being collected.
> 
> The JavaScript WeakRefs proposal could solve this, since then it could map an ID to a weak reference, ensuring the value can be collected if it is the last reference. The WeakRef executor can then also remove the entry from the map.

**Comment by cramforce** [comment]
I think the answer to this question is that WorkerDOM doesn't assume/support

**Comment by mdboom** [comment]
Thanks for your reply.  Looks like some interesting paths to pursue.  I don't have anything else to suggest, but I'll be watching this space.

Some context, just FYI: The use case I have in mind for this is for the [iodide project](https://github.com/iodide-project/iodide), which is a computational notebook for data science where the computation happens browser-side.  We want to provide easy and natural access to the DOM for visualization, which currently means running the user's code on the main thread.  However, this code may be long-running (and therefore blocks the UI) or buggy (there might be an infinite loop because the user is "programming experimentally"), so moving it onto a worker thread would really help with that.  In our case, it's less about improving frame rates and more about dealing with blocking and hanging on larger time scales.

**Comment by kristoferbaxter** [comment]
Very interesting project! I'm going to close this issue for now, but will create two issues to track the work of investigating each approach to memory management.
