### ISSUE TITLE
Changing the innerHTML might remove event listeners

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#620]
Code example:

```html
<amp-script layout="container" script="myscript">
  <div id="test">
    <p id="clickme">Click me</p>
  </div>
</amp-script>

<script id="myscript" type="text/plain" target="amp-script">
  const test = document.querySelector('#test');
  const clickme = document.querySelector('#clickme');
  clickme.addEventListener('click', () => test.innerHTML += 'a');
</script>
```

Only the first click is registered, the event stops firing after that.

After the first click, the innerHTML change presumably "recreated" `#clickme` and the event listener was lost.

**Comment by kristoferbaxter** [comment]
Slightly confused, this is the same behaviour a main thread implementation would do unless I'm missing some detail.

Can you recreate the expected functionality in a Glitch?

**Comment by fstanis** [comment]
Ugh, you're right, I just realized what I was doing.
