### ISSUE TITLE
Input's value doesn't resolve to anything unless I listed to "change"

### ISSUE THREAD

**Issue by fstanis** [ampproject/worker-dom#628]
```html
<amp-script layout="fixed-height" height="200" src="script.js">
  <div>
    <input type="text" id="input">
  </div>
  <p id="output"></p>
</amp-script>
```

If I do this:

```js
const output = document.querySelector('#output');
const input = document.querySelector('#input');

let c = 0;

setInterval(() => {
  output.textContent = `${input.value} ${c++}`;
}, 1000);
```

...then `input.value` is always empty.

However, adding `input.addEventListener('change', () => {})` to the code makes everything work as expected. It seems reading the value when no `change` event is registered means the value is never updated.

**Comment by philkrie** [comment]
I'm also seeing this issue in a client site when attempting to perform form validation. In such a use case, generally we should only have to apply an event listener to the submit button and then call the validation function. The code below should be sufficient to access the values in the fields after clicking on search_btn, but it only shows default values.

```javascript
const search_btn = document.getElementById('search_btn');
search_btn.addEventListener('click', function () {
  console.log(document.getElementById("from-input").value);  
  console.log(document.getElementById("to-input").value);  
});
```
Instead I have to do this:

```javascript
const search_btn = document.getElementById('search_btn');
const fromInput = document.getElementById('from-input');
const toInput = document.getElementById('to-input');

toInput.addEventListener('change', () => {});
fromInput.addEventListener('change', () => {});

search_btn.addEventListener('click', function () {
  console.log(fromInput.value);  
  console.log(toInput.value);  
});
```

The extra eventListeners don't make sense in a normal JS context.

**Comment by nainar** [comment]
Agreed that this is something we should fix on our end. Assigning this to @kristoferbaxter to take a look at.
