### ISSUE TITLE
Publish a release changelog

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/worker-dom#658]
The changelog should at least include all new APIs for a release.

**Comment by kristoferbaxter** [comment]
Right now the changelogs are published here:

https://github.com/ampproject/worker-dom/releases

Is the request to reformat the output to put new APIs more upfront?

**Comment by sebastianbenz** [comment]
Ah great - in that case the only thing missing is a link from the readme.

**Comment by kristoferbaxter** [comment]
Resolved here.

https://github.com/ampproject/worker-dom/commit/952680db1ab48d421e0fde66b7e3b56706349921
