### ISSUE TITLE
Clarify what browser versions are supported

### ISSUE THREAD

**Issue by sparhami** [ampproject/worker-dom#690]
It is unclear what browser versions are supported by WorkerDOM. This would ideally be made clear near the top of the README file. Is it everything that supports Web Workers or some other set (say last two major browser versions).

For example, WorkerDOM uses `NodeList.prototype.forEach`, which is [not supported](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility) in all browser versions that support Web Workers.

It is unclear whether or not this is something that should be fixed as it is unclear what browser versions are actually supported.

**Comment by kristoferbaxter** [comment]
Resolved with https://github.com/ampproject/worker-dom/commit/df59f5a1bddb10fc935ea779eadbbe285f37b691.
