### ISSUE TITLE
classList.toggle not strict enough

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/worker-dom#750]
`classList.toggle()` should throw an error when you include a space token you pass to it. 

i.e.
```js
el.classList.toggle('one two') //throws
```

worker-dom accepts the value, it also treats it as one token, so given 

```html
<div class="one"/>
```

if you try

```js
document.quertySelector('div').classList.toggle('one two')
```

you get

```html
<div class="one one two"/>
```

**Comment by kristoferbaxter** [comment]
Resolved with #830
