### ISSUE TITLE
Google amp-script tag not supported document.querySelector()

### ISSUE THREAD

**Issue by nishantp12345** [ampproject/worker-dom#752]
We tried some javascript predefined function in google amp "amp-script" tag but some functions not supported. 
For my information can you please share details of supported javascript predefined function?

**Comment by patrickkettner** [comment]
querySelector is supported, just not fully implemented. It only supports simple selectors (ie classname, ids, attributes, etc). It doesn’t support descendant selectors. 

[Here is information about supported APIs](https://github.com/ampproject/worker-dom/blob/master/README.md#which-browsers-are-supported)

**Comment by nishantp12345** [comment]
We tried this thing on my code node = document.querySelector('[class*="postid-"]'); but it's return undefined. On HTML page we added same selector to <body class="postid-41526"></body> body tag.

**Comment by patrickkettner** [comment]
Sadly that isn’t a simple selector (*= complicates it), it isn’t currently supported.

**Comment by nishantp12345** [comment]
ok. Is there document.head.appendChild is supported or not

**Comment by patrickkettner** [comment]
[as listed](https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md) in the [above reference](https://github.com/ampproject/worker-dom/issues/752#issuecomment-571478960) link, document.head is not available.
Keep in mind that in amp-script, you do not have access to the DOM of the executing page. you have access to the DOM that is within the <amp-script> element. As a result, there is no <head> element.

**Comment by nishantp12345** [comment]
ok. thanks for information
