### ISSUE TITLE
Allow document.getElementsByName()

### ISSUE THREAD

**Issue by morsssss** [ampproject/worker-dom#783]
Maybe this isn't used that much as getting items by selector, ID, or classname... but it's a logical way to grab form inputs. If it's easy to implement, then could we? It would also mean we had support for the basic DOM elements getting methods:

* document.getElementById()
* document.getElementsByClassName()
* document.getElementsByName()
* document.getElementsByTagName()

instead of omitting one.

(see also #782)

**Comment by kristoferbaxter** [comment]
Resolved with #833.
