### ISSUE TITLE
Support CJS or ES6 export

### ISSUE THREAD

**Issue by choumx** [ampproject/worker-dom#85]
Hit this while trying to integrate it into amphtml. E.g. in `@ampproject/worker-dom/dist/index.safe.js`:

Actual:
```js
var MainThread = (function (exports) {
...
```

Expected:
```js
module.exports = (function (exports) {
...
```

Or:
```js
export const MainThread = (function (exports) {
...
```

Exporting can prevent name collisions with "MainThread" in caller code.

**Comment by kristoferbaxter** [comment]
Spoke with @choumx offline and we determined the AMP build process doesn't support ES Modules fully or IIFE imports.

We'll need to create CJS exports for build systems like AMP uses.

Changing title to match what we plan to do to fix.

**Comment by choumx** [comment]
The Closure Compiler upgrade I'm working on appears to support (and require) ES modules in amphtml dependencies!

**Comment by choumx** [comment]
This is lower priority now.

**Comment by kristoferbaxter** [comment]
Closing this issue since it appears most modern toolchains can accept the ESM output. Will revisit if someone else is encountering the issue.
