### ISSUE TITLE
requestAnimationFrame not available in Safari

### ISSUE THREAD

**Issue by adriafolchmrf** [ampproject/worker-dom#853]
Hello,

We were trying to set up a project based on preact and we found a limitation if we were using the `amp-script` importing this code only in Safari, this error was being shown in the console.

![image](https://user-images.githubusercontent.com/19727464/80405215-9dc22200-88c2-11ea-837b-b8d259870e95.png)

We found that this was only being triggered if we were using react functional components with the `useEffect` hook, so that means that this code was working fine:

![image](https://user-images.githubusercontent.com/19727464/80405545-0dd0a800-88c3-11ea-9ea9-8a2f5d13ea98.png)

But however, when moving this to functional components, like this:

![image](https://user-images.githubusercontent.com/19727464/80406135-e0382e80-88c3-11ea-986e-75e4495eb245.png)

Is this a known issue? Or any further updates will solve this issue? We are using a third party library that is using the hooks itself to handle the components, so we can't really move everything to class components to bypass it.

**Comment by adriafolchmrf** [comment]
Hi @kristoferbaxter ,

Any updates regarding this ticket? 

Thanks

**Comment by oliverfernandez** [comment]
Hello @kristoferbaxter,

Do you have any update regarding this issue? React / Preact community is adopting fast hooks and functional components instead of class components, and this bug makes `<amp-script>` unusable

**Comment by kristoferbaxter** [comment]
I'm out on paternity leave right now, but will address when there is a bit of free time.

PRs are welcomed though! In this case a polyfill for requestAnimationFram/cancelAnimationFrame is needed.

**Comment by kristoferbaxter** [comment]
I filed a PR to address this, and manually verified it works in browsers that do not support request/cancel animation frame within Workers.

@choumx and @samouri can use this as a reference to address while I am out.

**Comment by diegofernandezmrf** [comment]
Just for reference, this is the PR: https://github.com/ampproject/worker-dom/pull/884

**Comment by diegofernandezmrf** [comment]
I see https://github.com/ampproject/worker-dom/pull/884 is merged 👏 
I couldn't find any information of the release process, is there an estimation or schedule for it?

**Comment by samouri** [comment]
@diegofernandezmrf: I don't think there is a formal release process. I'll perform a release today to get this fix out.

**Comment by samouri** [comment]
Just released v0.25.2 which should already be available on npm. This issue should be fixed now, but reopen/comment if you can still repro with the latest version.
