### ISSUE TITLE
Changing classList property results in [object Set]

### ISSUE THREAD

**Issue by morsssss** [ampproject/worker-dom#880]
This used to work fine; it seems to have broken recently!

Given a DOM Element like this:

`const el = document.getElementById('foo')`

If you do either 

`el.classList.remove('myClass')`

or

`el.classList.add('myClass')`

the element's class gets set to `[object Set]`

I've got an example of this [here on glitch](https://grove-thankful-ragdoll.glitch.me/finished_code/).

**Comment by jridgewell** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/29037, fixed by https://github.com/ampproject/worker-dom/pull/879.

**Comment by morsssss** [comment]
Excellent!

You sprung into action quickly ☺️
