### ISSUE TITLE
HTMLInputElement.click() Supported in table but using it results in "Error: click is not a function"

### ISSUE THREAD

**Issue by kruftindustries** [ampproject/worker-dom#888]
I am trying to obsfucate contact information so only humans can use the information. The bots constantly scrape new domains and new sites that are indexed by google so to avoid phishing scams, emails about "Give me bitcoins or xxx" unsolicited phone calls, etc.. I'd like to make it more challenging for the scripts that collect this information.

Maybe there is a better way to accomplish this?

**Comment by morsssss** [comment]
If WorkerDOM doesn't support this, we should at least change the compatibility table for now...

**Comment by patrickkettner** [comment]
fixed with #919
