### ISSUE TITLE
HTMLInputElement: prefilled value does not get synced to worker

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/worker-dom#912]
See the following [demo](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iaW5kIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iaW5kLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLXNjcmlwdCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtc2NyaXB0LTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICBoMSB7CiAgICAgIG1hcmdpbjogMXJlbTsKICAgIH0KICA8L3N0eWxlPgogIDxtZXRhIG5hbWU9ImFtcC1zY3JpcHQtc3JjIiBjb250ZW50PSJzaGEzODQtWnBwS1pwUkpXS1VHTndaZ255aUxCOFctYmJXUzcwc1J2Zk1hU0tZVHlFZVY3YktxajczMnZFWGhGM3NmZGl4NSBzaGEzODQtUkF4ejhXRDNiOEpkQlhabGJEYm9tam1DVkpscVpNYmticTg2c2Q2SXdxQTdNTi1aZzdOVE01QVlxQmlJMmt3bSBzaGEzODQtUVpjaHBQYXFtZGVSbTd4N1NGVXkyM2hoTjRvc1dxUXJfSDRrR1lQTmt4RV9ROTVZREEyTFAxY2wzVlVyVEJFNSBzaGEzODQtTTduUG0xSnNITWpmcGJfWEFOREZDN29NSi1TSGRNZWYyWS1HUlROa1FaR1dBZHJCeDBVOHVnZ3VNNWNpR0tRRCAiPgo8L2hlYWQ+Cjxib2R5PgoKICA8YW1wLXNjcmlwdCBsYXlvdXQ9ImNvbnRhaW5lciIgc2NyaXB0PSJkZW1vIj4KICAgIDxpbnB1dCBpZD0iaW5wdXQiIHZhbHVlPSJwcmVmaWxsZWQtdmFsdWUiPgogICAgPGJ1dHRvbiBpZD0iZ2V0LXZhbHVlIj4KICAgICAgR2V0IHByZWZpbGxlZCB2YWx1ZQogICAgPC9idXR0b24+CiAgPC9hbXAtc2NyaXB0PgogIDxzY3JpcHQgaWQ9ImRlbW8iIHR5cGU9InRleHQvcGxhaW4iIHRhcmdldD0iYW1wLXNjcmlwdCI+CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZ2V0LXZhbHVlJykuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoZSkgPT4gewogICAgCWNvbnNvbGUubG9nKCdQcmVmaWxsZWQgdmFsdWUnLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaW5wdXQnKS52YWx1ZSk7CiAgICB9KQogIDwvc2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K).

I expected to get `Prefilled value prefilled-value` in the console but only get `Prefilled value`.

**Comment by kristoferbaxter** [comment]
Resolved with #913
